О нейронных сетях
https://habr.com/ru/articles/312450/
https://habr.com/ru/articles/313216/
О функциях активации
https://ru.wikipedia.org/wiki/Функция_активации
Языки программирования для нейронных сетей
https://vc.ru/s/1420039-neyroseti/686392-samye-populyarnye-yazyki-programmirovaniya-v-sfere-neyrosetey
Как создавать нейронные сети?
https://vc.ru/u/1389654-machine-learning/588349-10-bibliotek-python-dlya-mashinnogo-obucheniya-i-iskusstvennogo-intellekta
Как доработать нейросеть?
https://habr.com/ru/articles/334944/
О компьютерном зрении
https://ru.wikipedia.org/wiki/Компьютерное_зрение
О сверточной нейронной сети
https://ru.wikipedia.org/wiki/Свёрточная_нейронная_сеть
https://habr.com/ru/articles/309508/
https://habr.com/ru/articles/348000/
https://habr.com/ru/articles/348028/
https://neurohive.io/ru/osnovy-data-science/glubokaya-svertochnaja-nejronnaja-set/ 
TensorFlow и Keras
https://www.tensorflow.org/overview?hl=ru
https://www.tensorflow.org/guide/keras?hl=ru
Image classification 
https://www.tensorflow.org/tutorials/images/classification?hl=ru
https://keras.io/examples/vision/image_classification_from_scratch/
Библиотека Opencv
https://habr.com/ru/articles/519454/
